#!/usr/bin/python3
def raise_exception():
    a = 10 / "asas"
    return a
